// 1 代表 网游竞技      2代表单机热游     3代表娱乐天地    4代表手游休闲        

export const contentData = [
    {title:'英雄联盟手游',url:'https://huyaimg.msstatic.com/cdnimage/game/6203-MS.png',belongTo:'4',id:'0001'},
    {title:'英雄联盟',url:'https://huyaimg.msstatic.com/cdnimage/game/1-MS.png',belongTo:'1',id:'0002'},
    {title:'王者荣耀',url:'	https://huyaimg.msstatic.com/cdnimage/game/2336-MS.png',belongTo:'4',id:'0003'},
    {title:'无悔华夏',url:'https://huyaimg.msstatic.com/cdnimage/game/7063-MS.png',belongTo:'1',id:'0004'},
    {title:'金铲铲之战',url:'https://huyaimg.msstatic.com/cdnimage/game/7185-MS.png',belongTo:'4',id:'0005'},
    {title:'和平精英',url:'https://huyaimg.msstatic.com/cdnimage/game/3203-MS.png',belongTo:'4',id:'0006'},
    {title:'绝地求生',url:'https://huyaimg.msstatic.com/cdnimage/game/2793-MS.png',belongTo:'1',id:'0007'},
    {title:'lol云顶之弈',url:'https://huyaimg.msstatic.com/cdnimage/game/5485-MS.png',belongTo:'1',id:'0008'},
    {title:'穿越火线',url:'https://huyaimg.msstatic.com/cdnimage/game/4-MS.png',belongTo:'1',id:'0009'},
    {title:'主机游戏',url:'https://huyaimg.msstatic.com/cdnimage/game/100032-MS.png',belongTo:'2',id:'0010'},
    
    {title:'综合手游',url:'https://huyaimg.msstatic.com/cdnimage/game/100029-MS.png',belongTo:'4',id:'0011'},
    {title:'暴雪专区',url:'https://huyaimg.msstatic.com/cdnimage/game/100043-MS.png',belongTo:'1',id:'0012'},
    {title:'CF手游',url:'https://huyaimg.msstatic.com/cdnimage/game/2413-MS.png',belongTo:'4',id:'0013'},
    {title:'地下城与勇士',url:'https://huyaimg.msstatic.com/cdnimage/game/2-MS.png',belongTo:'1',id:'0014'},
    {title:'魔兽世界',url:'https://huyaimg.msstatic.com/cdnimage/game/8-MS.png',belongTo:'1',id:'0015'},

    {title:'我的世界',url:'https://huyaimg.msstatic.com/cdnimage/game/1732-MS.png',belongTo:'2',id:'0016'},
    {title:'炉石传说',url:'https://huyaimg.msstatic.com/cdnimage/game/393-MS.png',belongTo:'1',id:'0017'},
    {title:'QQ飞车手游',url:'https://huyaimg.msstatic.com/cdnimage/game/2928-MS.png',belongTo:'1',id:'0018'},
    {title:'DOTA2',url:'https://huyaimg.msstatic.com/cdnimage/game/7-MS.png',belongTo:'1',id:'0019'},
    {title:'方舟',url:'https://huyaimg.msstatic.com/cdnimage/game/1997-MS.png',belongTo:'1',id:'0020'},
    {title:'泡泡卡丁车手游',url:'	https://huyaimg.msstatic.com/cdnimage/game/2620-MS.png',belongTo:'4',id:'0021'},

    {title:'火影忍者手游',url:'https://huyaimg.msstatic.com/cdnimage/game/2429-MS.png',belongTo:'4',id:'0022'},
    {title:'球球大作战',url:'https://huyaimg.msstatic.com/cdnimage/game/2411-MS.png',belongTo:'1',id:'0023'},
    {title:'csgo',url:'https://huyaimg.msstatic.com/cdnimage/game/862-MS.png',belongTo:'1',id:'0024'},
    {title:'QQ飞车',url:'https://huyaimg.msstatic.com/cdnimage/game/9-MS.png',belongTo:'1',id:'0025'},
    {title:'问道',url:'https://huyaimg.msstatic.com/cdnimage/game/107-MS.png',belongTo:'1',id:'0026'},

    {title:'逆战',url:'https://huyaimg.msstatic.com/cdnimage/game/135-MS.png',belongTo:'1',id:'0027'},
    {title:'三国杀',url:'https://huyaimg.msstatic.com/cdnimage/game/1669-MS.png',belongTo:'1',id:'0028'},
    {title:'梦三国',url:'https://huyaimg.msstatic.com/cdnimage/game/489-MS.png',belongTo:'1',id:'0029'},
    {title:'坦克世界',url:'https://huyaimg.msstatic.com/cdnimage/game/802-MS.png',belongTo:'2',id:'0030'},
    {title:'射击游戏',url:'https://huyaimg.msstatic.com/cdnimage/game/100141-MS.png',belongTo:'2',id:'0031'},
    {title:'飞扬神途',url:'https://huyaimg.msstatic.com/cdnimage/game/3077-MS.png',belongTo:'2',id:'0032'},

    {title:'明日之后',url:'	https://huyaimg.msstatic.com/cdnimage/game/3483-MS.png',belongTo:'2',id:'0033'},
    {title:'虚拟偶像',url:'https://huyaimg.msstatic.com/cdnimage/game/6055-MS.png',belongTo:'4',id:'0034'},
    {title:'COD手游',url:'https://huyaimg.msstatic.com/cdnimage/game/4769-MS.png',belongTo:'4',id:'0035'},
    {title:'环塔',url:'https://huyaimg.msstatic.com/cdnimage/game/6437-MS.png',belongTo:'1',id:'0036'},
    {title:'逃离塔克夫',url:'https://huyaimg.msstatic.com/cdnimage/game/3493-MS.png',belongTo:'2',id:'0037'},

    {title:'战争冲突',url:'https://huyaimg.msstatic.com/cdnimage/game/7449-MS.png',belongTo:'4',id:'0038'},
    {title:'庆余年手游',url:'https://huyaimg.msstatic.com/cdnimage/game/6939-MS.png',belongTo:'4',id:'0039'},
    {title:'DNF手游',url:'	https://huyaimg.msstatic.com/cdnimage/game/4921-MS.png',belongTo:'4',id:'0040'},
    {title:'炉石战旗',url:'https://huyaimg.msstatic.com/cdnimage/game/5751-MS.png',belongTo:'4',id:'0041'},
    {title:'欢乐斗地主',url:'https://huyaimg.msstatic.com/cdnimage/game/1749-MS.png',belongTo:'1',id:'0042'},

    {title:'APEX英雄',url:'	https://huyaimg.msstatic.com/cdnimage/game/5011-MS.png',belongTo:'1',id:'0043'},
    {title:'永恒之塔',url:'https://huyaimg.msstatic.com/cdnimage/game/446-MS.png',belongTo:'4',id:'0044'},
    {title:'英魂之刃',url:'https://huyaimg.msstatic.com/cdnimage/game/446-MS.png',belongTo:'2',id:'0045'},
    {title:'天涯明月刀手游',url:'https://huyaimg.msstatic.com/cdnimage/game/5115-MS.png',belongTo:'4',id:'0046'},
    {title:'御龙在天',url:'https://huyaimg.msstatic.com/cdnimage/game/675-MS.png',belongTo:'2',id:'0047'},


    {title:'起凡:群雄逐鹿',url:'https://huyaimg.msstatic.com/cdnimage/game/1612-MS.png',belongTo:'1',id:'0048'},
    {title:'天天狼人',url:'https://huyaimg.msstatic.com/cdnimage/game/2774-MS.png',belongTo:'1',id:'0049'},
    {title:'欢乐麻将',url:'	https://huyaimg.msstatic.com/cdnimage/game/1751-MS.png',belongTo:'4',id:'0050'},
    {title:'剑灵',url:'https://huyaimg.msstatic.com/cdnimage/game/897-MS.png',belongTo:'1',id:'0051'},
    {title:'冒险岛',url:'	https://huyaimg.msstatic.com/cdnimage/game/2243-MS.png',belongTo:'2',id:'0052'},
    {title:'失落的方舟',url:'https://huyaimg.msstatic.com/cdnimage/game/3058-MS.png',belongTo:'2',id:'0053'},
    {title:'彩虹岛online',url:'https://huyaimg.msstatic.com/cdnimage/game/683-MS.png',belongTo:'1',id:'0054'},

    {title:'守望先锋',url:'https://huyaimg.msstatic.com/cdnimage/game/2174-MS.png',belongTo:'1',id:'0055'},
    {title:'NBA2K系列',url:'https://huyaimg.msstatic.com/cdnimage/game/3959-MS.png',belongTo:'1',id:'0056'},
    {title:'御龙在天手游',url:'	https://huyaimg.msstatic.com/cdnimage/game/2568-MS.png',belongTo:'4',id:'0057'},
    {title:'英雄杀',url:'https://huyaimg.msstatic.com/cdnimage/game/2688-MS.png',belongTo:'1',id:'0058'},
    {title:'暗区突围',url:'	https://huyaimg.msstatic.com/cdnimage/game/7209-MS.png',belongTo:'2',id:'0059'},
    {title:'热血江湖',url:'https://huyaimg.msstatic.com/cdnimage/game/387-MS.png',belongTo:'1',id:'0060'},
    
    {title:'阴阳师',url:'	https://huyaimg.msstatic.com/cdnimage/game/2598-MS.png',belongTo:'4',id:'0061'},
    {title:'星际争霸',url:'	https://huyaimg.msstatic.com/cdnimage/game/5-MS.png',belongTo:'2',id:'0062'},
    {title:'骑马与砍杀',url:'https://huyaimg.msstatic.com/cdnimage/game/4783-MS.png',belongTo:'2',id:'0063'},
    {title:'恐惧之间',url:'https://huyaimg.msstatic.com/cdnimage/game/6679-MS.png',belongTo:'2',id:'0064'},
    {title:'龙之谷',url:'https://huyaimg.msstatic.com/cdnimage/game/15-MS.png',belongTo:'1',id:'0065'},

    {title:'传奇手游',url:'	https://huyaimg.msstatic.com/cdnimage/game/3130-MS.png',belongTo:'4',id:'0066'},
    {title:'Dayz独立版',url:'	https://huyaimg.msstatic.com/cdnimage/game/1125-MS.png',belongTo:'2',id:'0067'},
    {title:'斗罗大陆',url:'	https://huyaimg.msstatic.com/cdnimage/game/6745-MS.png',belongTo:'2',id:'0068'},
    {title:'幽灵线-东京',url:'https://huyaimg.msstatic.com/cdnimage/game/7669-MS.png',belongTo:'2',id:'0069'},

    {title:'战舰世界',url:'	https://huyaimg.msstatic.com/cdnimage/game/1947-MS.png',belongTo:'2',id:'0070'},
    {title:'部落冲突',url:'https://huyaimg.msstatic.com/cdnimage/game/1797-MS.png',belongTo:'1',id:'0071'},
    {title:'饥荒',url:'	https://huyaimg.msstatic.com/cdnimage/game/74-MS.png',belongTo:'2',id:'0072'},
    {title:'逆水寒',url:'	https://huyaimg.msstatic.com/cdnimage/game/2952-MS.png',belongTo:'1',id:'0073'},

    {title:'铁甲雄兵',url:'	https://huyaimg.msstatic.com/cdnimage/game/2765-MS.png',belongTo:'2',id:'0074'},
    {title:'剑仙世界3',url:'https://huyaimg.msstatic.com/cdnimage/game/7183-MS.png',belongTo:'1',id:'0075'},
    {title:'生死狙击',url:'https://huyaimg.msstatic.com/cdnimage/game/591-MS.png',belongTo:'2',id:'0076'},
    {title:'战地5',url:'https://huyaimg.msstatic.com/cdnimage/game/4371-MS.png',belongTo:'1',id:'0077'},
    {title:'寻仙',url:'https://huyaimg.msstatic.com/cdnimage/game/734-MS.png',belongTo:'1',id:'0078'},
    {title:'使命召唤',url:'https://huyaimg.msstatic.com/cdnimage/game/100137-MS.png',belongTo:'1',id:'0079'},
]